[package]
name = "my-cv-backend-rust"
version = "0.1.0"
authors = ["Josef Bauer <josef.bauer.1st@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
